---
# novachris_home - Self-Hosted Cloud Deployment
# Hauptplaybook für VM-Provisioning, Docker-Setup und App-Deployment
# "The Solid Base" - Stabilisierte Version mit Vault, Storage und intelligenter Automation

# ============================================================================
# PLAY 1: Profil-Setup und Konfiguration
# ============================================================================

- name: "PLAY 1: Profil-Setup und Konfiguration"
  hosts: localhost
  gather_facts: false
  vars:
    wiz_profile: "{{ wiz_profile | default('standard') }}"

  tasks:
    - name: "Setup: Zeige Profil-Auswahl"
      ansible.builtin.debug:
        msg:
          - "Profil: {{ wiz_profile }}"
          - "Deployment-Profile: {{ deployment_profiles[wiz_profile].description }}"

    - name: "Setup: Interaktive Abfrage bei Custom-Profil"
      block:
        - name: "Frage nach VMs"
          ansible.builtin.pause:
            prompt: "Welche VMs sollen erstellt werden? (gateway,office,ai-lab) [gateway,office]"
          register: vm_input

        - name: "Frage nach Apps"
          ansible.builtin.pause:
            prompt: "Welche Apps sollen deployed werden? (wireguard,traefik,paperless,n8n,postgresql,whisper,ollama) [paperless,n8n,postgresql]"
          register: app_input

        - name: "Setze Custom-Profil-Variablen"
          ansible.builtin.set_fact:
            custom_vms: "{{ (vm_input.user_input | default('gateway,office') | split(',')) }}"
            custom_apps: "{{ (app_input.user_input | default('paperless-ngx,n8n,postgresql') | split(',')) }}"
      when: wiz_profile == 'custom'

    - name: "Setup: Erstelle WIZARD_CONFIG Host"
      ansible.builtin.add_host:
        name: WIZARD_CONFIG
        ansible_connection: local
        groups:
          - wizard_config_group
        wiz_profile: "{{ wiz_profile }}"
        deployment_vms: "{{ deployment_profiles[wiz_profile].vms_to_create }}"
        deployment_apps: "{{ deployment_profiles[wiz_profile].apps_to_deploy }}"

# ============================================================================
# PLAY 2: Proxmox Host Vorbereitung
# ============================================================================

- name: "PLAY 2: Proxmox Host Vorbereitung und VM-Provisioning"
  hosts: proxmox_servers
  gather_facts: true
  become: true

  tasks:
    - name: "Proxmox: System-Setup"
      ansible.builtin.include_role:
        name: system_setup
      tags:
        - system_setup

    - name: "Proxmox: User-Management"
      ansible.builtin.include_role:
        name: user_management
      tags:
        - user_management

    - name: "Proxmox: Storage-Setup (Disk 2 Formatierung und Mounting)"
      ansible.builtin.include_role:
        name: storage_setup
      tags:
        - storage_setup

    - name: "Proxmox: VM-Provisioning"
      ansible.builtin.include_role:
        name: provision_guests
      tags:
        - provision_guests

# ============================================================================
# PLAY 3: Docker Setup auf Guest VMs
# ============================================================================

- name: "PLAY 3: Docker Setup auf Guest VMs"
  hosts: guest_vms
  gather_facts: true
  become: true
  serial: 1

  tasks:
    - name: "Docker: Installiere Docker Engine"
      ansible.builtin.include_role:
        name: docker_setup
      tags:
        - docker_setup

# ============================================================================
# PLAY 4: App Deployment
# ============================================================================

- name: "PLAY 4: App Deployment auf Guest VMs"
  hosts: guest_vms
  gather_facts: false
  become: true
  serial: 1

  tasks:
    - name: "Apps: Deployment"
      ansible.builtin.include_role:
        name: app_deployment
      tags:
        - app_deployment

# ============================================================================
# PLAY 5: QA und Validierung
# ============================================================================

- name: "PLAY 5: QA Smoke Tests"
  hosts: proxmox_servers
  gather_facts: false
  become: true

  tasks:
    - name: "QA: Smoke Tests"
      ansible.builtin.include_role:
        name: qa_smoke
      tags:
        - qa_smoke

# ============================================================================
# PLAY 6: Firewall-Aktivierung (AM ENDE - Nach allen Setup-Tasks)
# ============================================================================

- name: "PLAY 6: Firewall-Aktivierung und Sicherheit"
  hosts: proxmox_servers
  gather_facts: false
  become: true

  tasks:
    - name: "Firewall: Aktiviere PVE Firewall (am Ende)"
      ansible.builtin.include_role:
        name: system_setup
      vars:
        firewall_activation_only: true
      tags:
        - firewall
        - security

# ============================================================================
# PLAY 7: Abschluss und Reporting
# ============================================================================

- name: "PLAY 7: Deployment Abschluss"
  hosts: localhost
  gather_facts: false

  tasks:
    - name: "Report: Deployment Summary"
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "DEPLOYMENT ERFOLGREICH ABGESCHLOSSEN"
          - "=========================================="
          - "Profil: {{ hostvars['WIZARD_CONFIG']['wiz_profile'] }}"
          - "Erstellte VMs: {{ hostvars['WIZARD_CONFIG']['deployment_vms'] }}"
          - "Deployed Apps: {{ hostvars['WIZARD_CONFIG']['deployment_apps'] }}"
          - "Zeitstempel: {{ ansible_date_time.iso8601 }}"
          - "=========================================="
      tags:
        - report

    - name: "Report: Nächste Schritte"
      ansible.builtin.debug:
        msg:
          - ""
          - "Nächste Schritte:"
          - "1. Überprüfe die VMs: ssh admin@vm-gateway.example.local"
          - "2. Öffne die Dashboards:"
          - "   - Traefik: http://localhost:8080"
          - "   - Paperless: http://localhost:8000"
          - "   - N8N: http://localhost:5678"
          - "3. Konfiguriere WireGuard für Remote-Zugriff"
          - "4. Richte DNS-Einträge ein"
          - ""
      tags:
        - report
