all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    proxmox_servers:
      hosts:
        proxmox-host-01:
          ansible_host: 192.168.1.100
          ansible_user: root
          ansible_port: 22
